baseURL = "http://example.org/"
languageCode = "en-nz"
title = "Fanchao's Nest"
theme = "relax"
paginate = 10

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = -120

[[menu.main]]
name = "About"
url = "/about/"
weight = -110
